# Generated by Django 5.1.4 on 2024-12-20 15:41

import bulkremover.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to=bulkremover.models.get_og_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=bulkremover.models.get_pr_path)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
